### ISSUE TITLE
Not able to log-in running locally

### ISSUE THREAD

**Issue by Placemaster** [bootsie123/F1-Web-Viewer#67]
I am running the f1 web viewer  on my MacBook on port 3000.
Till the last race the majority of the options were working.
When launching the program the log-in box appears.
After filling-out the credentials it returns with the following error:
Request failed with status code 500

Macos Monterey
Version 12.3.1

F1TV Account (please complete the following information):

Pro Subscription
Netherlands

**Comment by Shamrayev365** [comment]
I'm having the same issue when self-hosting through Docker.

**Comment by markangeltrueman** [comment]
Got the same issue running with npm on a windows machine

console output...

FetchError: invalid json response body at https://api.formula1.com/v2/account/subscriber/authenticate/by-password reason: Unexpected token < in JSON at position 0
    at E:\F1-Web-Viewer\node_modules\node-fetch\lib\index.js:273:32

**Comment by timespacedecay** [comment]
I also get a 500 error on the web UI when trying to login to my self-hosted docker deployment.  Below are the logs:

```
FetchError: invalid json response body at https://api.formula1.com/v2/account/subscriber/authenticate/by-password reason: Unexpected token < in JSON at position 0
at /usr/src/app/node_modules/node-fetch/lib/index.js:273:32
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async /usr/src/app/functions/server.js:53:20 {
type: 'invalid-json'
}
```

**Comment by halil-erdogan** [comment]
Same issue for me when I run locally. Did anyone find the solution?

Edit: I am able to run https://github.com/iebb/F1WebViewer-SelfHosted

**Comment by sparky005** [comment]
I have the same error in the web app. Not using the self-hosted version, just logging in at https://f1webviewer.netlify.app/

EDIT: I see https://github.com/bootsie123/F1-Web-Viewer/issues/35 mentions that the web app is still not working, apologies for missing that.
